name: E-Mortalized
favicon: null
layout_spectrum: 0.26239094557240605
typography_spectrum: 0.7339041416998953
title: E-Mortalized
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-5100962-5
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.6639916931744665
  lightness: 0.22456780867651105
  saturation: 0.6357772573828697
  rhythmicContrast: 0.5372540485113859
purpose: []
